In [1]:
# Python Basics to Advanced in One Program

# === BASIC CONCEPTS ===

# Variables and Data Types
print("\n=== Basic Concepts ===")
name = input("Enter your name: ")
age = int(input("Enter your age: "))
print(f"Hello, {name}! You are {age} years old.")

# Conditional Statements
if age < 18:
    print("You are a minor.")
elif age < 60:
    print("You are an adult.")
else:
    print("You are a senior citizen.")

# Loops
print("\nCounting from 1 to 5 using a for loop:")
for i in range(1, 6):
    print(i, end=" ")
print("\n")

# === FUNCTIONS ===

def greet_user(name):
    """Greets the user with their name."""
    return f"Welcome, {name}!"

print("\nFunction Example:")
print(greet_user(name))

# === DATA STRUCTURES ===

# Lists
fruits = ["apple", "banana", "cherry"]
print("\nAvailable fruits:")
for fruit in fruits:
    print(fruit)

# Dictionaries
fruit_prices = {"apple": 100, "banana": 50, "cherry": 150}
print("\nFruit prices:")
for fruit, price in fruit_prices.items():
    print(f"{fruit.capitalize()}: {price} per kg")

# === FILE HANDLING ===

try:
    with open("user_data.txt", "w") as file:
        file.write(f"Name: {name}\nAge: {age}\n")
    print("\nUser data saved to 'user_data.txt'")
except Exception as e:
    print(f"Error writing to file: {e}")

# === EXCEPTION HANDLING ===

print("\nException Handling Example:")
try:
    num = int(input("Enter a number to divide 100: "))
    result = 100 / num
    print(f"100 divided by {num} is {result}")
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except ValueError:
    print("Error: Please enter a valid number.")
except Exception as e:
    print(f"Unexpected error: {e}")

# === ADVANCED CONCEPTS ===

# Classes and Objects
class Person:
    """A simple class to represent a person."""
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        return f"Hi, I'm {self.name} and I'm {self.age} years old!"

person = Person(name, age)
print("\n=== Object-Oriented Programming ===")
print(person.greet())

# Modules and Libraries
import math
print("\n=== Using Modules ===")
num = float(input("Enter a number to calculate its square root: "))
print(f"The square root of {num} is {math.sqrt(num)}")

# Using Libraries (Numpy Example)
print("\n=== Using Libraries ===")
import numpy as np

array = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", array)
print("Array Squared:", array ** 2)

# File Handling with Advanced Modes
try:
    with open("user_data.txt", "r") as file:
        print("\nReading from 'user_data.txt':")
        print(file.read())
except FileNotFoundError:
    print("Error: File not found!")

# === ADVANCED PROGRAMMING ===

# Lambda Functions
square = lambda x: x ** 2
print("\n=== Lambda Functions ===")
print(f"The square of 5 is {square(5)}")

# List Comprehensions
print("\n=== List Comprehensions ===")
squared_numbers = [x ** 2 for x in range(1, 6)]
print(f"Squares of numbers 1 to 5: {squared_numbers}")

# Generators
print("\n=== Generators ===")
def generate_numbers(n):
    for i in range(1, n + 1):
        yield i

print("Generated numbers (1 to 5):", list(generate_numbers(5)))

# Decorators
print("\n=== Decorators ===")
def decorator(func):
    def wrapper():
        print("Function is about to be called.")
        func()
        print("Function has been called.")
    return wrapper

@decorator
def decorated_function():
    print("This is the decorated function.")

decorated_function()

# Threading
print("\n=== Threading ===")
import threading

def print_numbers():
    for i in range(1, 6):
        print(f"Thread: {i}")

thread = threading.Thread(target=print_numbers)
thread.start()
thread.join()

# === END OF PROGRAM ===





=== Basic Concepts ===


Enter your name:  ss
Enter your age:  34


Hello, ss! You are 34 years old.
You are an adult.

Counting from 1 to 5 using a for loop:
1 2 3 4 5 


Function Example:
Welcome, ss!

Available fruits:
apple
banana
cherry

Fruit prices:
Apple: 100 per kg
Banana: 50 per kg
Cherry: 150 per kg

User data saved to 'user_data.txt'

Exception Handling Example:


Enter a number to divide 100:  45


100 divided by 45 is 2.2222222222222223

=== Object-Oriented Programming ===
Hi, I'm ss and I'm 34 years old!

=== Using Modules ===


Enter a number to calculate its square root:  3


The square root of 3.0 is 1.7320508075688772

=== Using Libraries ===
Numpy Array: [1 2 3 4 5]
Array Squared: [ 1  4  9 16 25]

Reading from 'user_data.txt':
Name: ss
Age: 34


=== Lambda Functions ===
The square of 5 is 25

=== List Comprehensions ===
Squares of numbers 1 to 5: [1, 4, 9, 16, 25]

=== Generators ===
Generated numbers (1 to 5): [1, 2, 3, 4, 5]

=== Decorators ===
Function is about to be called.
This is the decorated function.
Function has been called.

=== Threading ===
Thread: 1
Thread: 2
Thread: 3
Thread: 4
Thread: 5

=== Program Complete ===
Thank you for exploring Python Basics to Advanced!


In [3]:
# Full-Length PyTorch Basics to Advanced Program

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as transforms
import torchvision.datasets as datasets

print("\n=== PyTorch Full Program (Basics to Advanced) ===")

# === Tensors: Basics and Operations ===

# Creating Tensors
print("\n=== Creating Tensors ===")
tensor1 = torch.tensor([1.0, 2.0, 3.0])  # 1D Tensor
tensor2 = torch.zeros((3, 3))            # 3x3 Zero Tensor
tensor3 = torch.ones((3, 3))             # 3x3 Ones Tensor
tensor4 = torch.rand((2, 2))             # Random 2x2 Tensor

print(f"Tensor1: {tensor1}")
print(f"Tensor2 (zeros):\n{tensor2}")
print(f"Tensor3 (ones):\n{tensor3}")
print(f"Tensor4 (random):\n{tensor4}")

# Tensor Operations: Addition, Multiplication, etc.
print("\n=== Tensor Operations ===")
tensor_a = torch.tensor([2.0, 3.0, 4.0])
tensor_b = torch.tensor([1.0, 2.0, 3.0])

print(f"Addition: {tensor_a + tensor_b}")
print(f"Multiplication (element-wise): {tensor_a * tensor_b}")
print(f"Dot Product: {torch.dot(tensor_a, tensor_b)}")
print(f"Sum of tensor_a: {torch.sum(tensor_a)}")
print(f"Mean of tensor_a: {torch.mean(tensor_a)}")
print(f"Max of tensor_b: {torch.max(tensor_b)}")

# Reshaping and Flattening Tensors
print("\n=== Reshaping Tensors ===")
tensor5 = torch.arange(1, 10).reshape(3, 3)
print(f"Original Tensor (3x3):\n{tensor5}")
flattened_tensor = tensor5.flatten()
print(f"Flattened Tensor: {flattened_tensor}")

# Moving Tensors to GPU (if available)
if torch.cuda.is_available():
    print("\n=== Moving Tensors to GPU ===")
    gpu_tensor = tensor1.to("cuda")
    print(f"Tensor on GPU: {gpu_tensor}")

# === Automatic Differentiation ===

print("\n=== Automatic Differentiation (Autograd) ===")
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 4
y.backward()  # Compute gradients
print(f"x: {x}, Gradient (dy/dx): {x.grad}")

# === Datasets and DataLoader ===

print("\n=== Dataset and DataLoader ===")

# Custom Dataset (Simple Linear Dataset)
class CustomDataset(Dataset):
    def __init__(self):
        self.data = torch.arange(1, 101, dtype=torch.float32).reshape(-1, 1)
        self.labels = self.data * 2 + 1  # Simple linear relationship

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

# Viewing data from DataLoader
for batch_idx, (data, labels) in enumerate(dataloader):
    print(f"Batch {batch_idx + 1} | Data: {data.squeeze()} | Labels: {labels.squeeze()}")
    if batch_idx == 2:  # Show only 3 batches
        break

# === Neural Networks (Defining a Model) ===

print("\n=== Defining a Simple Neural Network ===")

# Simple Feedforward Neural Network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.layer1 = nn.Linear(1, 32)  # Linear layer (input 1 feature -> 32 units)
        self.layer2 = nn.Linear(32, 1)  # Linear layer (32 units -> output 1 feature)
        self.activation = nn.ReLU()     # ReLU activation function

    def forward(self, x):
        x = self.activation(self.layer1(x))
        x = self.layer2(x)
        return x

# Instantiate the model
model = SimpleNN()
print(f"Model Architecture:\n{model}")

# === Loss Function and Optimizer ===

print("\n=== Loss Function and Optimizer ===")
# Mean Squared Error Loss (MSE)
criterion = nn.MSELoss()
# Stochastic Gradient Descent Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

# === Training the Neural Network ===

print("\n=== Training the Neural Network ===")

# Training loop
epochs = 5
for epoch in range(epochs):
    epoch_loss = 0
    for data, labels in dataloader:
        # Forward pass
        predictions = model(data)
        loss = criterion(predictions, labels)

        # Backward pass
        optimizer.zero_grad()  # Zero gradients from previous step
        loss.backward()        # Compute gradients
        optimizer.step()       # Update parameters

        epoch_loss += loss.item()

    print(f"Epoch {epoch + 1}/{epochs} | Loss: {epoch_loss:.4f}")

# === Saving and Loading the Model ===

print("\n=== Saving and Loading the Model ===")
# Save model state_dict (weights)
torch.save(model.state_dict(), "simple_nn.pth")
print("Model saved to 'simple_nn.pth'.")

# Load the model
loaded_model = SimpleNN()
loaded_model.load_state_dict(torch.load("simple_nn.pth"))
loaded_model.eval()  # Set the model to evaluation mode
print("Model loaded successfully!")

# === Inference (Making Predictions) ===

print("\n=== Inference (Prediction) ===")
test_data = torch.tensor([[5.0]])  # Input data for prediction
prediction = loaded_model(test_data)
print(f"Prediction for input {test_data.item()}: {prediction.item():.4f}")

# === PyTorch Utilities ===

print("\n=== PyTorch Utilities ===")

# Checking for CUDA (GPU availability)
print(f"CUDA Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Current CUDA Device: {torch.cuda.current_device()}")
    print(f"CUDA Device Name: {torch.cuda.get_device_name(0)}")

# Setting random seeds for reproducibility
torch.manual_seed(42)
random_tensor = torch.rand(3, 3)
print(f"Random Tensor with Seed: \n{random_tensor}")

# === Advanced Topics ===

# Using Pre-trained Models (e.g., ResNet18 from torchvision)
print("\n=== Using Pre-Trained Models ===")
import torchvision.models as models

# Load a pre-trained ResNet18 model
resnet_model = models.resnet18(pretrained=True)
print(f"Pre-trained ResNet18 Model:\n{resnet_model}")

# Fine-tuning the pre-trained model
# For this, you can modify the final layers, but here we'll just demonstrate loading.
num_ftrs = resnet_model.fc.in_features
resnet_model.fc = nn.Linear(num_ftrs, 2)  # Modify final layer for 2 output classes
print("Modified ResNet18 (Final Layer Changed):\n", resnet_model)

# === Transfer Learning ===

print("\n=== Transfer Learning ===")
# Example: Freezing all layers except the final one
for param in resnet_model.parameters():
    param.requires_grad = False  # Freeze all layers

# Unfreeze the final layer
for param in resnet_model.fc.parameters():
    param.requires_grad = True

print("Transfer Learning Example: Freezing layers except the final layer.")

# === GPU Acceleration for Model Training ===

print("\n=== Using GPU for Training (if available) ===")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Move model to GPU if available
model = model.to(device)
test_data = test_data.to(device)  # Moving test data to the same device
prediction_gpu = model(test_data)
print(f"Prediction on GPU: {prediction_gpu.item():.4f}")

# === Batch Normalization (Advanced) ===

print("\n=== Batch Normalization ===")

class SimpleNNWithBN(nn.Module):
    def __init__(self):
        super(SimpleNNWithBN, self).__init__()
        self.layer1 = nn.Linear(1, 32)
        self.bn1 = nn.BatchNorm1d(32)  # Batch Normalization
        self.layer2 = nn.Linear(32, 1)

    def forward(self, x):
        x = self.bn1(self.layer1(x))  # Apply Batch Normalization after first layer
        x = self.layer2(x)
        return x

model_bn = SimpleNNWithBN()
print(f"Model with Batch Normalization:\n{model_bn}")





=== PyTorch Full Program (Basics to Advanced) ===

=== Creating Tensors ===
Tensor1: tensor([1., 2., 3.])
Tensor2 (zeros):
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Tensor3 (ones):
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor4 (random):
tensor([[0.1332, 0.9346],
        [0.5936, 0.8694]])

=== Tensor Operations ===
Addition: tensor([3., 5., 7.])
Multiplication (element-wise): tensor([ 2.,  6., 12.])
Dot Product: 20.0
Sum of tensor_a: 9.0
Mean of tensor_a: 3.0
Max of tensor_b: 3.0

=== Reshaping Tensors ===
Original Tensor (3x3):
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Flattened Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

=== Automatic Differentiation (Autograd) ===
x: 2.0, Gradient (dy/dx): 7.0

=== Dataset and DataLoader ===
Batch 1 | Data: tensor([23., 20., 60., 75., 78.,  7., 84., 50., 96., 90.]) | Labels: tensor([ 47.,  41., 121., 151., 157.,  15., 169., 101., 193., 181.])
Batch 2 | Data: tensor([88., 29., 36

C:\Users\somu\AppData\Local\Temp\ipykernel_22280\2213688764.py:144: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load("simple_nn.pth"))
c

Pre-trained ResNet18 Model:
ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (